# Javascript Node CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

jobs:
  lint:
    docker:
      - image: circleci/node:12
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - run: yarn lint:ci

      - store_test_results:
          path: reports
  test:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo
    steps:
      - restore_cache: # Restores the cached dependency.
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      # run tests!
      - run: yarn test:coverage --ci
      - store_artifacts:
          path: coverage
      - codecov/upload:
          file: coverage/*.json
          flags: backend

  test-unit:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo
    steps:
      - restore_cache: # Restores the cached dependency.
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      # run tests!
      - run: yarn test:coverage:unit --ci
      - store_artifacts:
          path: coverage-unit
      - codecov/upload:
          file: coverage-unit/*.json
          flags: backend_unit

  test-integration:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo
    steps:
      - restore_cache: # Restores the cached dependency.
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      # run tests!
      - run: yarn test:coverage:integration --ci
      - store_artifacts:
          path: coverage-integration
      - codecov/upload:
          file: coverage-integration/*.json
          flags: backend_integration

workflows:
  version: 2.1
  test: # name this as you want
    jobs:
      - lint
      - test:
          requires:
            - lint # wait for lint job to complete successfully before starting
          # see circleci.com/docs/2.0/workflows/ for more examples.
      - test-unit:
          requires:
            - lint
      - test-integration:
          requires:
            - lint
